### PR TITLE
Feature/fun 509 oauth2 token handler

### PR DESCRIPTION
**Pull request by btamas**
Related to https://oat-sa.atlassian.net/browse/FUN-509

Goal is to implement https://oauth2.thephpleague.com/authorization-server/refresh-token-grant/
The different between the required oauth2 request and the original OAT JWT token request is:
**Request:**
- refresh token is called `refresh_token` in the request
- request format is FormData instead of json
- `client_id` and `grant_type` should be sent, but this is handled with the existing `refreshTokenParameters`

**Response:**
- access token is called `access_token` in the response
- refresh token is sent in the response and it is called `refresh_token`
- `expires_in` is sent in the response and this is the TTL of the access token in seconds

These differences could be handled with some conditions, so I made the decision to do not create a new token handler, but modify the existing one.

### Test:
- run tests and check them, because they covers everything

(I tested it with @peetya on his local environment, where this modification will be necessary)

Now, it is not possible to test in a working environment, because it is just a small part of big refactoring.

### CODE REVIEW

**Comment by oatymart** [comment]
> Goal is to implement https://oauth2.thephpleague.com/authorization-server/refresh-token-grant/

I'd like to know what is the *real* goal, what problem will it solve for us? Is it more secure? More convenient?  ... Is it because we could scope the requests with `client_id` or `scope`, somehow preventing cheating?

The other main difference I notice from reading the code is that we'll receive back `expires_in` - but I [added a util](https://github.com/oat-sa/tao-core-sdk-fe/pull/103) last year which had a similar purpose, to extract TTL from the existing JWT response payload. It's convenient to receive the named value from the server but is the result any different?

**Comment by krampstudio** [comment]
In the Solar test runner we've even started to use another approach (integrated with env management) where the refresh token is never exposed directly but set using an HTTPOnly cookie, to prevent leaking it. Maybe we should align on the mechanism to use.

**Comment by jsconan** [comment]
The code looks ok, and the unit tests are passing. I have no issue with the proposal, but yes, looking at the other comments I agree we should align on the solution. We need to apply a unified way otherwise we'll have different implementations for each consumer ;)

**Comment by btamas** [comment]
> > Goal is to implement https://oauth2.thephpleague.com/authorization-server/refresh-token-grant/
> 
> I'd like to know what is the _real_ goal, what problem will it solve for us? Is it more secure? More convenient? ... Is it because we could scope the requests with `client_id` or `scope`, somehow preventing cheating?

During GCP migration of the scoring project, a new environment management system will be used and there will be a dedicated auth server. This server will do the auth related tasks (token creation, password check) and it will be separated from the BE server, that sends session related configurations. This auth server will use oauth2, what was a decision earlier, but manual scoring is unique, because we should support user/password login. To implement it in the oauth2 context, we have to follow the standard. This standard contains the `client_id`, `scope` and `grant_type`. Oauth2 can return with any token, without specific requirement, but in our projects, we will use JWT, so we can use JWT token modules.
I also have problem with a redundant `expires_in` <-> jwt token `exp`, but the oauth2 protocol send the token ttl, so we should use it. 

> 
> The other main difference I notice from reading the code is that we'll receive back `expires_in` - but I [added a util](https://github.com/oat-sa/tao-core-sdk-fe/pull/103) last year which had a similar purpose, to extract TTL from the existing JWT response payload. It's convenient to receive the named value from the server but is the result any different?

**Comment by btamas** [comment]
@krampstudio @jsconan @oatymart Do you need any other info to approve this PR?

**Review by oatymart — APPROVED** [review]
Code looks clean and simple. Tests are passing and cover almost everything.

- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] Documentation is updated according to changes (if applicable)

**Review by jsconan — APPROVED** [review]
The code is ok and passes the unit tests.
In the end, we would still need to unify the APIs, but as per the discussion above, the added feature should be acceptable. 

Note: tested only via unit tests.

**Review Checklist**
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable) - **_Tested only via unit test_**
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic

**Pull request merged**
